version: '3'
services:
  lite-server:
    image: node
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ../task-2/static:/home/node/app
    command: bash -c "npm install && npm start"
    deploy:
      replicas: 3
    networks:
      - loadbalancing

  json-server:
    image: node
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ../task-3/static:/home/node/app
    command: bash -c "npm install && npm start"
    deploy:
      replicas: 3
    networks:
      - loadbalancing

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./static/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - loadbalancing
    depends_on:
      - lite-server
      - json-server

networks:
  loadbalancing:
